spring:
  profiles:
    active: ${APP_ENV:development}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost/checkmob}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:secret}
  jpa:
    open-in-view: false
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:mailhog}
    password: ${MAIL_PASSWORD:null}
    from_address: ${MAIL_NOREPLY:no-reply@checkmob.co.mz}
    from_name: ${MAIL_FROMNAME:CheckMob}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  flyway:
    locations: classpath:/db/migration
